# Supported Funding Platforms

Use this section to specify the funding model platforms supported by your project.

## GitHub Sponsors

You can support us on GitHub Sponsors by sponsoring one of our team members:
- [user1](https://github.com/user1)
- [user2](https://github.com/user2)

## Patreon

Support us on Patreon:
- [PatreonUsername](https://www.patreon.com/PatreonUsername)

## Open Collective

Support us on Open Collective:
- [OpenCollectiveUsername](https://opencollective.com/OpenCollectiveUsername)

## Ko-fi

Support us on Ko-fi:
- [Ko-fiUsername](https://ko-fi.com/Ko-fiUsername)

## Tidelift

Support us through Tidelift:
- [TideliftPlatformName/PackageName](https://tidelift.com/subscription/pkg/npm/babel)

## Community Bridge

Support us on Community Bridge:
- [CommunityBridgeProjectName](https://communitybridge.org/projects/CommunityBridgeProjectName)

## Liberapay

Support us on Liberapay:
- [LiberapayUsername](https://liberapay.com/LiberapayUsername)

## IssueHunt

Support us on IssueHunt:
- [IssueHuntUsername](https://issuehunt.io/r/IssueHuntUsername)

## LFX Crowdfunding

Support us on LFX Crowdfunding:
- [LFX CrowdfundingProjectName](https://lfx_crowdfunding.org/projects/LFX%20CrowdfundingProjectName)

## Polar

Support us on Polar:
- [PolarUsername](https://www.polar.com/PolarUsername)

## Buy Me a Coffee

Support us on Buy Me a Coffee:
- [BuyMeACoffeeUsername](https://www.buymeacoffee.com/BuyMeACoffeeUsername)

## Custom

If you prefer other platforms or methods to support us, you can use the following custom sponsorship URLs:
- [CustomLink1](https://customlink1.com)
- [CustomLink2](https://customlink2.com)


